version: '3'
services:
  wordpress:
    build:
      context: ./../../docker-images
      dockerfile: DockerfileWordPress
      args:
        WORKING_DIR: ${APP_NAME}
    container_name: ${APP_NAME}-wordpress
    volumes:
      - .:/var/www/html/${APP_NAME}
      - ../../config/php.ini:/usr/local/etc/php/conf.d/php.ini
    user: '1000'
    restart: always
    environment:
     WORDPRESS_DB_HOST: cozmoslabs-mysql
     WORDPRESS_DB_USER: root
     WORDPRESS_DB_PASSWORD: password
     WORDPRESS_DB_NAME: ${APP_NAME}
     XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}

networks:
  default:
    external:
      name: cozmoslabs-docker_default
